### PR TITLE
Improve German translation

### PR DESCRIPTION
**Pull request by chrizzzle**
I noticed some mistakes in the German translation, so I made some improvements.

### CODE REVIEW

**Comment by boldninja** [comment]
Can you not translate All-in-One Blockchain Solutions - Solutions to  Lösungen?

**Comment by faustbrian** [comment]
@chrizzzle Could you change `All-in-One Blockchain Lösungen` back to `All-in-One Blockchain Solutions`? This is the kicker and slogan so it shouldn't be translated.

**Comment by chrizzzle** [comment]
Ok, changed it

**Comment by faustbrian** [comment]
Thanks!

**Pull request merged**
