### PR TITLE
ARK.IO Korean Translation

### PR DESCRIPTION
**Pull request by etham-ju**
Not 100% but 99%.
Some of the text is not predictable with only text.
I will have to edit more if needed after it gets deployed to website.

### CODE REVIEW

**Comment by etham-ju** [comment]
i cant find any issue here. can you check this for me?

**Comment by faustbrian** [comment]
You can resolve the conflicts with the GitHub Desktop application if you are not to savy with the git terminal.

**Comment by etham-ju** [comment]
i tried @faustbrian :( cannot desktop application ...

**Comment by faustbrian** [comment]
If you are unable to resolve the conflicts please open a new PR.

**Comment by etham-ju** [comment]
i will try @faustbrian

**Pull request closed without merging**
