### PR TITLE
ru.json added, 30% done

### PR DESCRIPTION
**Pull request by palevoo**
started translating to russian, hopefully will be able to finish it soon

### CODE REVIEW

**Comment by faustbrian** [comment]
Think it would be good to merge this once it is at around 80% to have actual use. What do you think @boldninja?

**Comment by boldninja** [comment]
Yes I agree. Thank you for your work so far @palevoo

**Comment by 0toierance** [comment]
@palevoo If you need a second opinion on translations, feel free to tag me.

**Comment by boldninja** [comment]
Also things like brands and slogans shouldn't be translated ( ARK, SmartBridge, Point. Click. Blockchain., All-in-One Blockchain Solutions) .

**Comment by 0toierance** [comment]
Noticed that some of those brands/slogans were in fact translated.

**Comment by faustbrian** [comment]
@0toierance I've added some new translations https://github.com/ArkEcosystem/ARK.io-Translations/blob/master/translations/en.json#L286-L292.

Any ETA on when you will be done with the full translation of the file?

**Comment by palevoo** [comment]
will have some spare time this weekend, ty for the info on slogans and brands

**Comment by faustbrian** [comment]
Any progress on this? @palevoo @0toierance

**Comment by 0toierance** [comment]
Can someone get give me access to edit the repo, I have edited nearly 100 lines.

**Comment by faustbrian** [comment]
You will have to send a PR like everyone else.

**Pull request closed without merging**
